const searchData = {
  recipes: [
    {
      vegetarian: true,
      vegan: false,
      glutenFree: true,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 13,
      gaps: "no",
      lowFodmap: false,
      aggregateLikes: 8,
      spoonacularScore: 66.0,
      healthScore: 14.0,
      creditsText: "coffeebean",
      license: "spoonacular's terms",
      sourceName: "spoonacular",
      pricePerServing: 159.28,
      extendedIngredients: [
        {
          id: 19165,
          aisle: "Baking",
          image: "cocoa-powder.png",
          consistency: "solid",
          name: "cocoa powder",
          nameClean: "hersheys cocoa",
          original: "1 tablespoon cocoa powder",
          originalString: "1 tablespoon cocoa powder",
          originalName: "cocoa powder",
          amount: 1.0,
          unit: "tablespoon",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
            metric: {
              amount: 1.0,
              unitShort: "Tbsp",
              unitLong: "Tbsp",
            },
          },
        },
        {
          id: 1012,
          aisle: "Cheese",
          image: "cottage-cheese.jpg",
          consistency: "solid",
          name: "cottage cheese",
          nameClean: "cottage cheese",
          original: "1 cup quark or cottage cheese",
          originalString: "1 cup quark or cottage cheese",
          originalName: "quark or cottage cheese",
          amount: 1.0,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1123,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg.png",
          consistency: "solid",
          name: "eggs",
          nameClean: "egg",
          original: "3 eggs",
          originalString: "3 eggs",
          originalName: "eggs",
          amount: 3.0,
          unit: "",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 3.0,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 3.0,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 19911,
          aisle: "Cereal",
          image: "maple-syrup.png",
          consistency: "liquid",
          name: "maple syrup",
          nameClean: "maple syrup",
          original: "maple syrup",
          originalString: "maple syrup",
          originalName: "maple syrup",
          amount: 2.0,
          unit: "servings",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 2.0,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 8120,
          aisle: "Cereal",
          image: "rolled-oats.jpg",
          consistency: "solid",
          name: "rolled oats",
          nameClean: "rolled oats",
          original: "1 cup rolled oats",
          originalString: "1 cup rolled oats",
          originalName: "rolled oats",
          amount: 1.0,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
      ],
      id: 157259,
      title: "Cocoa Protein Pancakes",
      author: "coffeebean",
      readyInMinutes: 15,
      servings: 2,
      sourceUrl: "http://spoonacular.com/-1383233228884",
      image: "https://spoonacular.com/recipeImages/157259-556x370.jpg",
      imageType: "jpg",
      summary:
        'Cocoa Protein Pancakes might be just the morn meal you are searching for. For <b>$1.59 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>410 calories</b>, <b>26g of protein</b>, and <b>14g of fat</b> each. From preparation to the plate, this recipe takes approximately <b>15 minutes</b>. Head to the store and pick up cocoa powder, maple syrup, rolled oats, and a few other things to make it today. It is a good option if you\'re following a <b>gluten free and vegetarian</b> diet. Try <a href="https://spoonacular.com/recipes/creamy-cocoa-hemp-protein-smoothie-585692">Creamy Cocoa Hemp Protein Smoothie</a>, <a href="https://spoonacular.com/recipes/cocoa-pancakes-760520">Cocoa Pancakes</a>, and <a href="https://spoonacular.com/recipes/cocoa-pancakes-443253">Cocoa Pancakes</a> for similar recipes.',
      cuisines: [],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: ["gluten free", "lacto ovo vegetarian"],
      occasions: [],
      instructions:
        "<p><strong>1.</strong> Blend the rolled oats in a blender or food processor until you have a fine powder. Mix in the cocoa powder.<br></p><p> <strong>2.</strong> Blend the ground oats/cocoa powder with the cottage cheese (or quark, if you can find it) and eggs.</p><p> <strong>3.</strong> Pour the thick batter into a hot, oiled skillet and use the back of a spoon to form round pancakes.</p><p> <strong>4</strong>. Flip the pancakes once the sides are firm and turning brown.<strong>.</strong></p><p> <strong>5.  </strong>Serve with maple syrup.</p>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Blend the rolled oats in a blender or food processor until you have a fine powder.",
              ingredients: [
                {
                  id: 8120,
                  name: "rolled oats",
                  localizedName: "rolled oats",
                  image: "rolled-oats.jpg",
                },
              ],
              equipment: [
                {
                  id: 404771,
                  name: "food processor",
                  localizedName: "food processor",
                  image: "food-processor.png",
                },
                {
                  id: 404726,
                  name: "blender",
                  localizedName: "blender",
                  image: "blender.png",
                },
              ],
            },
            {
              number: 2,
              step: "Mix in the cocoa powder.",
              ingredients: [
                {
                  id: 19165,
                  name: "cocoa powder",
                  localizedName: "cocoa powder",
                  image: "cocoa-powder.png",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Blend the ground oats/cocoa powder with the cottage cheese (or quark, if you can find it) and eggs.",
              ingredients: [
                {
                  id: 1012,
                  name: "cottage cheese",
                  localizedName: "cottage cheese",
                  image: "cottage-cheese.jpg",
                },
                {
                  id: 19165,
                  name: "cocoa powder",
                  localizedName: "cocoa powder",
                  image: "cocoa-powder.png",
                },
                {
                  id: 93676,
                  name: "quark",
                  localizedName: "quark",
                  image: "white-cream-fluffy.jpg",
                },
                {
                  id: 1123,
                  name: "egg",
                  localizedName: "egg",
                  image: "egg.png",
                },
                {
                  id: 8120,
                  name: "oats",
                  localizedName: "oats",
                  image: "rolled-oats.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: "Pour the thick batter into a hot, oiled skillet and use the back of a spoon to form round pancakes.",
              ingredients: [],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 5,
              step: "Flip the pancakes once the sides are firm and turning brown..",
              ingredients: [],
              equipment: [],
            },
            {
              number: 6,
              step: "Serve with maple syrup.",
              ingredients: [
                {
                  id: 19911,
                  name: "maple syrup",
                  localizedName: "maple syrup",
                  image: "maple-syrup.png",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/cocoa-protein-pancakes-157259",
    },
  ],
};
const getInfoRecipeData = {
  vegetarian: true,
  vegan: false,
  glutenFree: true,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 13,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 8,
  spoonacularScore: 66.0,
  healthScore: 14.0,
  creditsText: "coffeebean",
  license: "spoonacular's terms",
  sourceName: "spoonacular",
  pricePerServing: 159.28,
  extendedIngredients: [
    {
      id: 19165,
      aisle: "Baking",
      image: "cocoa-powder.png",
      consistency: "solid",
      name: "cocoa powder",
      nameClean: "hersheys cocoa",
      original: "1 tablespoon cocoa powder",
      originalString: "1 tablespoon cocoa powder",
      originalName: "cocoa powder",
      amount: 1.0,
      unit: "tablespoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 1012,
      aisle: "Cheese",
      image: "cottage-cheese.jpg",
      consistency: "solid",
      name: "cottage cheese",
      nameClean: "cottage cheese",
      original: "1 cup quark or cottage cheese",
      originalString: "1 cup quark or cottage cheese",
      originalName: "quark or cottage cheese",
      amount: 1.0,
      unit: "cup",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "solid",
      name: "eggs",
      nameClean: "egg",
      original: "3 eggs",
      originalString: "3 eggs",
      originalName: "eggs",
      amount: 3.0,
      unit: "",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 19911,
      aisle: "Cereal",
      image: "maple-syrup.png",
      consistency: "liquid",
      name: "maple syrup",
      nameClean: "maple syrup",
      original: "maple syrup",
      originalString: "maple syrup",
      originalName: "maple syrup",
      amount: 2.0,
      unit: "servings",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 8120,
      aisle: "Cereal",
      image: "rolled-oats.jpg",
      consistency: "solid",
      name: "rolled oats",
      nameClean: "rolled oats",
      original: "1 cup rolled oats",
      originalString: "1 cup rolled oats",
      originalName: "rolled oats",
      amount: 1.0,
      unit: "cup",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
  ],
  id: 157259,
  title: "Cocoa Protein Pancakes",
  author: "coffeebean",
  readyInMinutes: 15,
  servings: 2,
  sourceUrl: "http://spoonacular.com/-1383233228884",
  image: "https://spoonacular.com/recipeImages/157259-556x370.jpg",
  imageType: "jpg",
  summary:
    'Cocoa Protein Pancakes might be just the morn meal you are searching for. For <b>$1.59 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>410 calories</b>, <b>26g of protein</b>, and <b>14g of fat</b> each. From preparation to the plate, this recipe takes approximately <b>15 minutes</b>. Head to the store and pick up cocoa powder, maple syrup, rolled oats, and a few other things to make it today. It is a good option if you\'re following a <b>gluten free and vegetarian</b> diet. Try <a href="https://spoonacular.com/recipes/creamy-cocoa-hemp-protein-smoothie-585692">Creamy Cocoa Hemp Protein Smoothie</a>, <a href="https://spoonacular.com/recipes/cocoa-pancakes-760520">Cocoa Pancakes</a>, and <a href="https://spoonacular.com/recipes/cocoa-pancakes-443253">Cocoa Pancakes</a> for similar recipes.',
  cuisines: [],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["gluten free", "lacto ovo vegetarian"],
  occasions: [],
  winePairing: {},
  instructions:
    "<p><strong>1.</strong> Blend the rolled oats in a blender or food processor until you have a fine powder. Mix in the cocoa powder.<br></p><p> <strong>2.</strong> Blend the ground oats/cocoa powder with the cottage cheese (or quark, if you can find it) and eggs.</p><p> <strong>3.</strong> Pour the thick batter into a hot, oiled skillet and use the back of a spoon to form round pancakes.</p><p> <strong>4</strong>. Flip the pancakes once the sides are firm and turning brown.<strong>.</strong></p><p> <strong>5.  </strong>Serve with maple syrup.</p>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Blend the rolled oats in a blender or food processor until you have a fine powder.",
          ingredients: [
            {
              id: 8120,
              name: "rolled oats",
              localizedName: "rolled oats",
              image: "rolled-oats.jpg",
            },
          ],
          equipment: [
            {
              id: 404771,
              name: "food processor",
              localizedName: "food processor",
              image: "food-processor.png",
            },
            {
              id: 404726,
              name: "blender",
              localizedName: "blender",
              image: "blender.png",
            },
          ],
        },
        {
          number: 2,
          step: "Mix in the cocoa powder.",
          ingredients: [
            {
              id: 19165,
              name: "cocoa powder",
              localizedName: "cocoa powder",
              image: "cocoa-powder.png",
            },
          ],
          equipment: [],
        },
        {
          number: 3,
          step: "Blend the ground oats/cocoa powder with the cottage cheese (or quark, if you can find it) and eggs.",
          ingredients: [
            {
              id: 1012,
              name: "cottage cheese",
              localizedName: "cottage cheese",
              image: "cottage-cheese.jpg",
            },
            {
              id: 19165,
              name: "cocoa powder",
              localizedName: "cocoa powder",
              image: "cocoa-powder.png",
            },
            {
              id: 93676,
              name: "quark",
              localizedName: "quark",
              image: "white-cream-fluffy.jpg",
            },
            {
              id: 1123,
              name: "egg",
              localizedName: "egg",
              image: "egg.png",
            },
            {
              id: 8120,
              name: "oats",
              localizedName: "oats",
              image: "rolled-oats.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 4,
          step: "Pour the thick batter into a hot, oiled skillet and use the back of a spoon to form round pancakes.",
          ingredients: [],
          equipment: [
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 5,
          step: "Flip the pancakes once the sides are firm and turning brown..",
          ingredients: [],
          equipment: [],
        },
        {
          number: 6,
          step: "Serve with maple syrup.",
          ingredients: [
            {
              id: 19911,
              name: "maple syrup",
              localizedName: "maple syrup",
              image: "maple-syrup.png",
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: "https://spoonacular.com/cocoa-protein-pancakes-157259",
};
const getSimilarRecipes = [
  {
    id: 209128,
    title: "Dinner Tonight: Grilled Romesco-Style Pork",
    imageType: "jpg",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "http://www.seriouseats.com/recipes/2008/07/grilled-romesco-style-pork-salad-recipe.html",
  },
  {
    id: 31868,
    title: "Dinner Tonight: Chickpea Bruschetta",
    imageType: "jpg",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://www.seriouseats.com/recipes/2009/06/dinner-tonight-chickpea-bruschetta-babbo-nyc-recipe.html",
  },
];
